name: TriggerUpdateMetadata

on:
    push:
        path:
            - meta/**
    workflow_dispatch:

jobs:
    TriggerUpdateMeta:
        uses:
            Joshua-XIV/MyDalamudPlugin/.github/workflows/Update_Metadata.yml@main
        secrets: inheirt